import { ArrowLeft, CheckCircle2, Printer, ShieldAlert } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { dummyResponses } from '../data/dummyResponses';

const readReport = () => {
  const stored = localStorage.getItem('analysisResult');
  if (stored) return JSON.parse(stored);
  return dummyResponses.secure;
};

const ReportProduct = () => {
  const navigate = useNavigate();
  const response = readReport();
  const metadata = response.analysis || response;
  const predictions = response.ai_predictions || {};
  const features = response.traffic_features || {};
  const config = response.security_configuration || {};
  const assessment = response.security_assessment || {};
  const meanLength = features.len_mean ?? features.packet_len_mean;
  const getPrediction = (item) => (typeof item === 'object' && item !== null ? item.label : item) || 'Unknown';
  const getConfidence = (item, fallback) => { const value = typeof item === 'object' && item !== null ? item.confidence : fallback; return typeof value === 'number' ? Math.round(value <= 1 ? value * 100 : value) : 0; };

  return (
    <div className="p-5 sm:p-8 print:bg-white print:text-black">
      <div className="mx-auto max-w-5xl">
        <div className="mb-8 flex items-center justify-between print:hidden"><button type="button" onClick={() => navigate('/')} className="inline-flex items-center gap-2 text-sm font-semibold text-soc-textSecondary transition hover:-translate-x-1 hover:text-soc-primaryLight"><ArrowLeft className="h-4 w-4" />Back to dashboard</button><button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-lg border border-soc-primary/30 bg-soc-primary/10 px-4 py-2 text-sm font-semibold text-soc-primaryLight transition hover:-translate-y-0.5 hover:border-soc-primary/60 hover:bg-soc-primary/20"><Printer className="h-4 w-4" />Export report</button></div>
        <header className="relative mb-8 overflow-hidden rounded-3xl border border-soc-border bg-gradient-to-br from-soc-card to-[#234633] p-6 shadow-xl shadow-[#102019]/20 sm:p-8"><div className="pointer-events-none absolute -right-16 -top-20 h-52 w-52 rounded-full bg-soc-primary/10 blur-3xl" /><div className="relative"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-soc-primary">IPsec AI · Security assessment</p><div className="mt-3 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-bold tracking-tight text-soc-text sm:text-4xl">Security report</h1><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 font-mono text-sm text-soc-textSecondary"><span>{metadata.filename || 'Unknown capture'}</span><span>{metadata.id || 'Live analysis'}</span><span>{metadata.created_at ? new Date(metadata.created_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' }) : 'Generated today'}</span></div></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-soc-success/30 bg-soc-success/10 px-3 py-1.5 text-xs font-bold uppercase tracking-wider text-soc-success"><span className="h-1.5 w-1.5 rounded-full bg-soc-success" />{metadata.status || 'Completed'}</span></div></div></header>

        <section className="grid grid-cols-1 gap-6 border-b border-soc-border pb-8 lg:grid-cols-[260px_1fr]"><div className="group rounded-xl border border-soc-primary/25 bg-gradient-to-br from-soc-primary/10 to-soc-card p-6 text-center transition-all duration-300 hover:border-soc-primary/50 hover:shadow-lg hover:shadow-soc-primary/5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-soc-textMuted">Security score</p><p className="mt-4 text-6xl font-bold text-soc-text transition-transform duration-300 group-hover:scale-105">{assessment.score ?? 0}</p><p className="mt-1 text-sm text-soc-textMuted">out of 100</p><p className={`mt-5 inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-bold uppercase tracking-wider ${assessment.status === 'Secure' ? 'border-soc-success/30 bg-soc-success/10 text-soc-success' : assessment.status === 'Warning' ? 'border-soc-warning/30 bg-soc-warning/10 text-soc-warning' : 'border-soc-danger/30 bg-soc-danger/10 text-soc-danger'}`}><ShieldAlert className="h-3.5 w-3.5" />{assessment.status || 'Unknown'}</p></div><div className="rounded-xl border border-soc-border bg-soc-card p-6 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-soc-textMuted">Executive summary</p><p className="mt-3 max-w-2xl text-lg leading-8 text-soc-textSecondary">The analyzed capture shows <strong className="text-soc-text">{getPrediction(predictions.mode)}</strong> IPsec traffic using <strong className="text-soc-text">{getPrediction(predictions.cipher)}</strong> encryption. This report separates model confidence from the security score so the posture is clear and auditable.</p><div className="mt-5 flex flex-wrap gap-2 text-xs text-soc-textMuted"><span className="rounded-full bg-soc-background px-3 py-1.5">Evidence-led analysis</span><span className="rounded-full bg-soc-background px-3 py-1.5">AI-assisted detection</span></div></div></section>

        <section className="border-b border-soc-border py-8"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-soc-textMuted">AI detection</p><h2 className="mt-1 text-xl font-semibold text-soc-text">What the model identified</h2></div><span className="text-xs text-soc-textMuted">Model confidence</span></div><div className="grid gap-3 sm:grid-cols-3">{[['IPsec mode', predictions.mode, predictions.mode_confidence], ['Traffic profile', predictions.traffic_type, predictions.traffic_confidence], ['Encryption', predictions.cipher, predictions.cipher_confidence]].map(([label, value, fallback]) => <div key={label} className="group rounded-lg border border-soc-border bg-soc-card p-4 transition-all duration-300 hover:-translate-y-1 hover:border-soc-accent/40"><p className="text-xs text-soc-textMuted">{label}</p><div className="mt-2 flex items-end justify-between gap-3"><p className="font-semibold text-soc-text">{getPrediction(value)}</p><p className="font-mono text-sm text-soc-accent">{getConfidence(value, fallback)}%</p></div><div className="mt-3 h-1.5 rounded-full bg-soc-background"><div className="h-1.5 rounded-full bg-soc-accent transition-all duration-700 group-hover:bg-soc-primary" style={{ width: `${getConfidence(value, fallback)}%` }} /></div></div>)}</div></section>

        <section className="border-b border-soc-border py-8"><h2 className="mb-5 text-xl font-semibold text-soc-text">Traffic characteristics</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Packets', features.packet_count?.toLocaleString() || 'N/A'], ['Avg length', meanLength ? `${meanLength.toFixed(1)} B` : 'N/A'], ['Avg IAT', features.iat_mean ? `${(features.iat_mean * 1000).toFixed(1)} ms` : 'N/A'], ['Entropy', features.entropy_mean?.toFixed(2) || 'N/A']].map(([label, value]) => <div key={label} className="rounded-lg border border-soc-border bg-soc-card p-4"><p className="text-xs text-soc-textMuted">{label}</p><p className="mt-2 text-xl font-bold text-soc-text">{value}</p></div>)}</div></section>

        <section className="border-b border-soc-border py-8"><h2 className="mb-5 text-xl font-semibold text-soc-text">Security configuration</h2><div className="overflow-hidden rounded-lg border border-soc-border"><table className="w-full text-left text-sm"><tbody>{[['PFS', config.pfs_enabled ? 'Enabled' : 'Disabled'], ['Replay protection', config.replay_protection ? 'Enabled' : 'Disabled'], ['DH group', config.dh_group || 'N/A'], ['AES key size', config.key_size_bits ? `${config.key_size_bits}-bit` : 'N/A'], ['SHA-1', config.sha1_used ? 'Detected' : 'Not detected'], ['Key lifetime', config.key_lifetime ? `${config.key_lifetime >= 3600 ? config.key_lifetime / 3600 : config.key_lifetime}${config.key_lifetime >= 3600 ? ' hours' : 's'}` : 'N/A']].map(([label, value]) => <tr key={label} className="border-b border-soc-border last:border-0"><td className="px-4 py-3 text-soc-textSecondary">{label}</td><td className="px-4 py-3 text-right font-semibold text-soc-text">{value}</td></tr>)}</tbody></table></div></section>

        <section className="grid gap-8 py-8 md:grid-cols-2"><div><h2 className="mb-5 text-xl font-semibold text-soc-text">Findings</h2><div className="space-y-3">{(assessment.findings || []).map((finding, index) => <div key={index} className="flex gap-3 rounded-lg border border-soc-border bg-soc-card p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 flex-shrink-0 text-soc-success" /><div><p className="font-semibold text-soc-text">{finding.title || finding}</p>{finding.description && <p className="mt-1 text-sm text-soc-textSecondary">{finding.description}</p>}</div></div>)}</div></div><div><h2 className="mb-5 text-xl font-semibold text-soc-text">Recommendations</h2><div className="space-y-3">{(assessment.recommendations || []).map((recommendation, index) => <div key={index} className="rounded-lg border border-soc-border bg-soc-card p-4"><p className="font-semibold text-soc-text">{recommendation.title || recommendation}</p>{recommendation.description && <p className="mt-1 text-sm text-soc-textSecondary">{recommendation.description}</p>}</div>)}</div></div></section>
        <footer className="border-t border-soc-border pt-5 text-xs text-soc-textMuted">Generated by IPsec AI Security Analyzer</footer>
      </div>
    </div>
  );
};

export default ReportProduct;
